import { gql } from "apollo-server-express";
import { readFileSync } from "fs";
import { DocumentNode } from "graphql";
import { resolve } from "path";

/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import { Resolvers } from "@server/graphql.generated";

export class ServerModule {
  public readonly typeDefs: DocumentNode;

  public constructor(
    graphqlFilename: string,
    public readonly resolvers: Resolvers
  ) {
    this.typeDefs = gql(
      readFileSync(resolve(__dirname, graphqlFilename), "utf8")
    );
  }
}
