// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var getCursorPosition, hiraganaToKatakana, k, setCursorPosition, v, _ref, _results;
    getCursorPosition = function(element) {
      var el, pos, sel, selLength;
      el = $(element).get(0);
      pos = 0;
      if ("selectionStart" in el) {
        pos = el.selectionStart;
      } else if ("selection" in document) {
        el.focus();
        sel = document.selection.createRange();
        selLength = document.selection.createRange().text.length;
        sel.moveStart("character", -el.value.length);
        pos = sel.text.length - selLength;
      }
      return pos;
    };
    setCursorPosition = function(element, pos) {
      var el;
      el = $(element).get(0);
      el.focus();
      if ("selectionStart" in el) {
        return element.selectionStart = element.selectionEnd = pos;
      }
    };
    hiraganaToKatakana = function(str) {
      str = str.split("").map(function(c) {
        var code;
        code = c.charCodeAt(0);
        if (code >= 0x3041 && code <= 0x3094) {
          return String.fromCharCode(code + (0x30A1 - 0x3041));
        } else {
          return c;
        }
      });
      return str.join("");
    };
    $.fn.kana = function(options) {
      var input, lastPos, opts, _ref;
      opts = $.extend({}, $.fn.kana.defaults, options);
      if ((_ref = opts.mode) !== "hiragana" && _ref !== "katakana" && _ref !== "romaji") {
        throw "Mode must be either hiragana, katakana or romaji.";
      }
      input = "";
      lastPos = getCursorPosition(this);
      this.unbind("input");
      this.on("input", function() {
        var currentPos, table, tmp, val, _ref1, _ref2;
        if ((_ref1 = opts.mode) !== "hiragana" && _ref1 !== "katakana") {
          return;
        }
        table = $.fn.kana.tables[opts.mode];
        currentPos = getCursorPosition(this);
        val = $(this).val();
        if (currentPos !== lastPos + 1) {
          input = "";
        }
        input += val[currentPos - 1] || "";
        tmp = input;
        while (tmp.length) {
          if (tmp in table) {
            val = val.slice(0, currentPos - tmp.length) + table[tmp] + val.slice(currentPos, val.length);
            $(this).val(val);
            setCursorPosition(this, currentPos - tmp.length + table[tmp].length);
            if ((_ref2 = table[tmp][0]) === "ん" || _ref2 === "ン" || _ref2 === "っ" || _ref2 === "ッ") {
              input = table[tmp][1];
            } else {
              input = "";
            }
            break;
          }
          tmp = tmp.slice(1, input.length + 1 || 9e9);
        }
        return lastPos = currentPos;
      });
      return this;
    };
    $.fn.kana.defaults = {
      "mode": "hiragana"
    };
    $.fn.kana.tables = {
      hiragana: {
        a: "あ",
        i: "い",
        u: "う",
        e: "え",
        o: "お",
        ka: "か",
        ki: "き",
        ku: "く",
        ke: "け",
        ko: "こ",
        kya: "きゃ",
        kyi: "きぃ",
        kyu: "きゅ",
        kyo: "きょ",
        kye: "きぇ",
        sa: "さ",
        si: "し",
        shi: "し",
        su: "す",
        se: "せ",
        so: "そ",
        sha: "しゃ",
        sya: "しゃ",
        syi: "しぃ",
        shu: "しゅ",
        syu: "しゅ",
        sho: "しょ",
        syo: "しょ",
        she: "しぇ",
        sye: "しぇ",
        ta: "た",
        ti: "ち",
        chi: "ち",
        tu: "つ",
        tsu: "つ",
        te: "て",
        to: "と",
        cha: "ちゃ",
        tya: "ちゃ",
        tyi: "ちぃ",
        tsi: "つぃ",
        chu: "ちゅ",
        tyu: "ちゅ",
        cho: "ちょ",
        tyo: "ちょ",
        che: "ちぇ",
        tye: "ちぇ",
        na: "な",
        ni: "に",
        nu: "ぬ",
        ne: "ね",
        no: "の",
        nya: "にゃ",
        nyi: "にぃ",
        nyu: "にゅ",
        nye: "にぇ",
        nyo: "にょ",
        ha: "は",
        hi: "ひ",
        hu: "ふ",
        he: "へ",
        ho: "ほ",
        hya: "ひゃ",
        hyi: "ひぃ",
        hyu: "ひゅ",
        hye: "ひぇ",
        hyo: "ひょ",
        fa: "ふぁ",
        fi: "ふぃ",
        fu: "ふ",
        fe: "ふぇ",
        fo: "ふぉ",
        fya: "ふゃ",
        fyi: "ふぃ",
        fyu: "ふゅ",
        fye: "ふぇ",
        fyo: "ふょ",
        ma: "ま",
        mi: "み",
        mu: "む",
        me: "め",
        mo: "も",
        mya: "みゃ",
        myi: "みぃ",
        myu: "みゅ",
        mye: "みぇ",
        myo: "みょ",
        ya: "や",
        yi: "い",
        yu: "ゆ",
        ye: "いぇ",
        yo: "よ",
        ra: "ら",
        ri: "り",
        ru: "る",
        re: "れ",
        ro: "ろ",
        rya: "りゃ",
        ryi: "りぃ",
        ryu: "りゅ",
        rye: "りぇ",
        ryo: "りょ",
        la: "ら",
        li: "り",
        lu: "る",
        le: "れ",
        lo: "ろ",
        lya: "りゃ",
        lyi: "りぃ",
        lyu: "りゅ",
        lye: "りぇ",
        lyo: "りょ",
        wa: "わ",
        wi: "うぃ",
        wu: "う",
        we: "うぇ",
        wo: "を",
        wya: "うゃ",
        wyi: "ゐ",
        wyu: "うゅ",
        wye: "ゑ",
        wyo: "うょ",
        da: "だ",
        di: "ぢ",
        du: "づ",
        de: "で",
        "do": "ど",
        dya: "ぢゃ",
        dyi: "ぢぃ",
        dyu: "ぢゅ",
        dye: "ぢぇ",
        dyo: "ぢょ",
        pa: "ぱ",
        pi: "ぴ",
        pu: "ぷ",
        pe: "ぺ",
        po: "ぽ",
        pya: "ぴゃ",
        pyi: "ぴぃ",
        pyu: "ぴゅ",
        pye: "ぴぇ",
        pyo: "ぴょ",
        ga: "が",
        gi: "ぎ",
        gu: "ぐ",
        ge: "げ",
        go: "ご",
        gya: "ぎゃ",
        gyi: "ぎぃ",
        gyu: "ぎゅ",
        gye: "ぎぇ",
        gyo: "ぎょ",
        ja: "じゃ",
        ji: "じ",
        ju: "じゅ",
        je: "じぇ",
        jo: "じょ",
        jya: "じゃ",
        jyi: "じぃ",
        jyu: "じゅ",
        jye: "じぇ",
        jyo: "じょ",
        za: "ざ",
        zi: "じ",
        zu: "ず",
        ze: "ぜ",
        zo: "ぞ",
        zya: "じゃ",
        zyi: "じぃ",
        zyu: "じゅ",
        zye: "じぇ",
        zyo: "じょ",
        va: "ヴぁ",
        vi: "ヴぃ",
        vu: "ヴ",
        ve: "ヴぇ",
        vo: "ヴぉ",
        vya: "ヴゃ",
        vyu: "ヴゅ",
        vye: "ヴぃぇ",
        vyo: "ヴょ",
        ba: "ば",
        bi: "び",
        bu: "ぶ",
        be: "べ",
        bo: "ぼ",
        bya: "びゃ",
        byi: "びぃ",
        byu: "びゅ",
        bye: "びぇ",
        byo: "びょ",
        xa: "ぁ",
        xi: "ぃ",
        xu: "ぅ",
        xe: "ぇ",
        xo: "ぉ",
        xya: "ゃ",
        xyi: "ぃ",
        xyu: "ゅ",
        xye: "ぇ",
        xyo: "ょ",
        rr: "っr",
        tt: "っt",
        yy: "っy",
        pp: "っp",
        ss: "っs",
        dd: "っd",
        ff: "っf",
        gg: "っg",
        hh: "っh",
        jj: "っj",
        kk: "っk",
        ll: "ll",
        zz: "っz",
        xx: "っx",
        cc: "っc",
        vv: "っv",
        bb: "っb",
        nn: "ん",
        mm: "っm",
        nq: "んq",
        nw: "んw",
        nr: "んr",
        nt: "んt",
        np: "んp",
        ns: "んs",
        nd: "んd",
        nf: "んf",
        ng: "んg",
        nh: "んh",
        nj: "んj",
        nk: "んk",
        nl: "んl",
        nz: "んz",
        nx: "んx",
        nc: "んc",
        nv: "んv",
        nb: "んb",
        nm: "んm",
        "1": "１",
        "2": "２",
        "3": "３",
        "4": "４",
        "5": "５",
        "6": "６",
        "7": "７",
        "8": "８",
        "9": "９",
        "0": "０",
        " ": "　",
        "-": "ー",
        "_": "＿",
        ".": "。",
        ",": "、",
        ":": "：",
        ";": "；",
        "'": "’",
        "*": "＊",
        "<": "＜",
        ">": "＞",
        "|": "｜",
        "+": "＋",
        "!": "！",
        "\"": "”",
        "#": "＃",
        "%": "％",
        "&": "＆",
        "(": "（",
        ")": "）",
        "=": "＝",
        "?": "？",
        "@": "＠",
        "$": "＄",
        "¥": "￥",
        "{": "｛",
        "}": "｝",
        "[": "「",
        "]": "」",
        "/": "／",
        "\\": "＼",
        "n1": "ん１",
        "n2": "ん２",
        "n3": "ん３",
        "n4": "ん４",
        "n5": "ん５",
        "n6": "ん６",
        "n7": "ん７",
        "n8": "ん８",
        "n9": "ん９",
        "n0": "ん０",
        "n ": "ん　",
        "n-": "んー",
        "n_": "ん＿",
        "n.": "ん。",
        "n,": "ん、",
        "n:": "ん：",
        "n;": "ん；",
        "n'": "ん’",
        "n*": "ん＊",
        "n<": "ん＜",
        "n>": "ん＞",
        "n|": "ん｜",
        "n£": "ん£",
        "n€": "ん€",
        "n¡": "ん¡",
        "n+": "ん＋",
        "n!": "ん！",
        "n\"": "ん”",
        "n#": "ん＃",
        "n%": "ん％",
        "n&": "ん＆",
        "n(": "ん（",
        "n)": "ん）",
        "n=": "ん＝",
        "n?": "ん？",
        "n@": "ん＠",
        "n$": "ん＄",
        "n¥": "ん￥",
        "n{": "ん｛",
        "n}": "ん｝",
        "n[": "ん「",
        "n]": "ん」",
        "n/": "ん／",
        "n\\": "ん＼",
        "nå": "んå",
        "nä": "んä",
        "nö": "んö",
        "nø": "んø",
        "næ": "んæ"
      }
    };
    $.fn.kana.tables["katakana"] = {};
    _ref = $.fn.kana.tables["hiragana"];
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      _results.push($.fn.kana.tables["katakana"][k] = hiraganaToKatakana(v));
    }
    return _results;
  });

}).call(this);
