/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import { Resolvers } from "@server/graphql.generated";

export const CORE_RESOLVERS: Resolvers = {
  Query: {
    serverVersion: (): string => "blah",
  },
};
