/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import {
  MutationSubmitSuggestionArgs,
  Resolvers,
  SubmitSuggestionResult,
} from "@server/graphql.generated";

export const SUGGESTIONS_BOX_RESOLVERS: Resolvers = {
  Mutation: {
    submitSuggestion: (
      _: unknown,
      { suggestion }: MutationSubmitSuggestionArgs
    ): SubmitSuggestionResult => {
      console.log("suggestion:", suggestion);
      return {
        success: !!suggestion,
      };
    },
  },
};
