/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import {
  MutationSubmitSuggestionArgs,
  Resolvers,
  SubmitSuggestionResult,
} from "@server/graphql.generated";

import { ServerContext } from "@server/context";

export const SUGGESTIONS_BOX_RESOLVERS: Resolvers = {
  Mutation: {
    submitSuggestion: async (
      _: unknown,
      { clientVersion, suggestion, userAgent }: MutationSubmitSuggestionArgs,
      { dataSources: { database } }: ServerContext
    ): Promise<SubmitSuggestionResult> => {
      try {
        await database.addSuggestion({
          clientVersion,
          message: suggestion,
          userAgent,
        });

        return {
          success: true,
        };
      } catch (err) {
        console.error("submitSuggestion", err);
        return {
          success: false,
        };
      }
    },
  },
};
