version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build database
          command: yarn db:update
      - run:
          name: Export data from database
          command: yarn build-data
      - run:
          name: Ensure repository data files are up to date
          command: git diff --exit-code data/*
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Build code
          command: yarn build
