version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13.13.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Generate Prisma library
          command: yarn prisma generate
      - run:
          name: Build database
          command: yarn db:create
      - run:
          name: Audit data
          command: yarn db:audit
      - run:
          name: Export data from database
          command: yarn db:export
      - run:
          name: Ensure repository data files are up to date
          command: git diff --exit-code data/*
      - run:
          name: Extract react-intl message definitions
          command: yarn i18n:extract
      - run:
          name: Ensure repository i18n files are up to date
          command: git diff --exit-code i18n/*
      - run:
          name: Codegen
          command: yarn codegen
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Check project boundaries
          command: yarn check-project-boundaries
      - run:
          name: Build code
          command: yarn build
