/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import {
  Resolvers,
  StandardCounterCollection,
  UserCounterCollection,
} from "@server/graphql.generated";

type SomeCounterCollection = StandardCounterCollection | UserCounterCollection;

export const COUNTER_COLLECTIONS_RESOLVERS: Resolvers = {
  CounterCollection: {
    __resolveType: (
      obj: SomeCounterCollection
    ): "UserCounterCollection" | "StandardCounterCollection" => {
      if ("dateCreated" in obj) {
        return "UserCounterCollection";
      }

      return "StandardCounterCollection";
    },
  },
  Query: {
    standardCounterCollections: (): StandardCounterCollection[] => [],
    userCounterCollections: (): UserCounterCollection[] => [],
  },
};
