declare module "*.json" {
  /**
   * Disabling this because it's difficult to get an accurate typing
   * for the AST contents of the JSON files here, and because the risk
   * for abuse is extremely low since these are generated by an external
   * tool and passed into a library owned by that tool.
   */
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
  const values: Record<string, any>;
  export default values;
}
