export const MIN_USER_FEEDBACK_MESSAGE_LENGTH = 20;
export const MAX_USER_FEEDBACK_MESSAGE_LENGTH = 1000;

export const MIN_PASSWORD_LENGTH = 8;

export const ONE_SECOND = 1000;
export const ONE_MINUTE = ONE_SECOND * 60;
