/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import {
  Resolvers,
  MutationSubmitBugReportArgs,
  SubmitBugReportResult,
} from "@server/graphql.generated";

export const BUG_REPORT_RESOLVERS: Resolvers = {
  Mutation: {
    submitBugReport: (
      _: unknown,
      { message, os, browser, userAgent }: MutationSubmitBugReportArgs
    ): SubmitBugReportResult => {
      console.log("bug report:", message, os, browser, userAgent);
      return {
        success: true,
      };
    },
  },
};
