/**
 * On new checkouts, you're going to be missing this file. This
 * is autogenerated and therefore not checked into the repository.
 * Generate this file automatically using `yarn gql:codegen`.
 */
import {
  Resolvers,
  MutationSubmitBugReportArgs,
  SubmitBugReportResult,
} from "@server/graphql.generated";

import { ServerContext } from "@server/context";

export const BUG_REPORT_RESOLVERS: Resolvers = {
  Mutation: {
    submitBugReport: async (
      _: unknown,
      {
        message,
        os,
        browser,
        userAgent,
        clientVersion,
      }: MutationSubmitBugReportArgs,
      { dataSources: { database } }: ServerContext
    ): Promise<SubmitBugReportResult> => {
      try {
        await database.addBugReport({
          browser,
          clientVersion,
          message,
          os,
          userAgent,
        });
        return {
          success: true,
        };
      } catch (err) {
        console.error("submitBugReport error", err);
        return {
          success: false,
        };
      }
    },
  },
};
