PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE item_counters (item_id STRING REFERENCES items (item_id), counter_id STRING REFERENCES counters (counter_id));
INSERT INTO item_counters VALUES('cow','頭');
INSERT INTO item_counters VALUES('horse','頭');
INSERT INTO item_counters VALUES('gorilla','頭');
INSERT INTO item_counters VALUES('whale','頭');
INSERT INTO item_counters VALUES('rabbit','匹');
INSERT INTO item_counters VALUES('dog','匹');
INSERT INTO item_counters VALUES('cat','匹');
INSERT INTO item_counters VALUES('sheep','匹');
INSERT INTO item_counters VALUES('deer','匹');
INSERT INTO item_counters VALUES('otter','匹');
INSERT INTO item_counters VALUES('credit card','枚');
INSERT INTO item_counters VALUES('playing card','枚');
INSERT INTO item_counters VALUES('paper','枚');
INSERT INTO item_counters VALUES('photo','枚');
INSERT INTO item_counters VALUES('chicken','羽');
INSERT INTO item_counters VALUES('penguin','羽');
INSERT INTO item_counters VALUES('rabbit','羽');
INSERT INTO item_counters VALUES('origami crane','羽');
INSERT INTO item_counters VALUES('elephant','頭');
INSERT INTO item_counters VALUES('washing machine','台');
INSERT INTO item_counters VALUES('oven','台');
INSERT INTO item_counters VALUES('microwave','台');
INSERT INTO item_counters VALUES('car','台');
INSERT INTO item_counters VALUES('bed','台');
INSERT INTO item_counters VALUES('textbook','冊');
INSERT INTO item_counters VALUES('dictionary','冊');
INSERT INTO item_counters VALUES('notebook','冊');
INSERT INTO item_counters VALUES('magazine','冊');
INSERT INTO item_counters VALUES('book','冊');
INSERT INTO item_counters VALUES('bat','羽');
INSERT INTO item_counters VALUES('year','年');
INSERT INTO item_counters VALUES('month','月');
INSERT INTO item_counters VALUES('month','ヶ月');
INSERT INTO item_counters VALUES('floor (building)','階');
INSERT INTO item_counters VALUES('storey','階');
INSERT INTO item_counters VALUES('years old','歳');
INSERT INTO item_counters VALUES('time (occurrences)','回');
INSERT INTO item_counters VALUES('occurrence','回');
INSERT INTO item_counters VALUES('soda can','缶');
INSERT INTO item_counters VALUES('beer can','缶');
INSERT INTO item_counters VALUES('empty can','缶');
INSERT INTO item_counters VALUES('can of bug spray','缶');
INSERT INTO item_counters VALUES('can of hair spray','缶');
INSERT INTO item_counters VALUES('spray paint','缶');
INSERT INTO item_counters VALUES('can of soup','缶');
INSERT INTO item_counters VALUES('song','曲');
INSERT INTO item_counters VALUES('tune','曲');
INSERT INTO item_counters VALUES('bathroom','ヶ所');
INSERT INTO item_counters VALUES('shopping mall','ヶ所');
INSERT INTO item_counters VALUES('cinema','ヶ所');
INSERT INTO item_counters VALUES('location','ヶ所');
INSERT INTO item_counters VALUES('place','ヶ所');
INSERT INTO item_counters VALUES('country','ヶ国');
INSERT INTO item_counters VALUES('nation','ヶ国');
INSERT INTO item_counters VALUES('yen','円');
INSERT INTO item_counters VALUES('slice of pizza','切れ');
INSERT INTO item_counters VALUES('filet','切れ');
INSERT INTO item_counters VALUES('slice of cake','切れ');
INSERT INTO item_counters VALUES('cut of meat','切れ');
INSERT INTO item_counters VALUES('slice of sashimi','切れ');
INSERT INTO item_counters VALUES('bite of food','口');
INSERT INTO item_counters VALUES('sip of water','口');
INSERT INTO item_counters VALUES('couple (people)','組');
INSERT INTO item_counters VALUES('group of friends','組');
INSERT INTO item_counters VALUES('melody','曲');
INSERT INTO item_counters VALUES('jingle','曲');
INSERT INTO item_counters VALUES('radio','台');
INSERT INTO item_counters VALUES('receipt','枚');
INSERT INTO item_counters VALUES('week','週');
INSERT INTO item_counters VALUES('lap','周');
INSERT INTO item_counters VALUES('circuit','周');
INSERT INTO item_counters VALUES('round','周');
INSERT INTO item_counters VALUES('tint','色');
INSERT INTO item_counters VALUES('hue','色');
INSERT INTO item_counters VALUES('colour','色');
INSERT INTO item_counters VALUES('seat','席');
INSERT INTO item_counters VALUES('meeting','席');
INSERT INTO item_counters VALUES('assembly','席');
INSERT INTO item_counters VALUES('banquet','席');
INSERT INTO item_counters VALUES('bar of chocolate','枚');
INSERT INTO item_counters VALUES('man','人');
INSERT INTO item_counters VALUES('woman','人');
INSERT INTO item_counters VALUES('coworker','人');
INSERT INTO item_counters VALUES('roommate','人');
INSERT INTO item_counters VALUES('person','人');
INSERT INTO item_counters VALUES('person','名');
INSERT INTO item_counters VALUES('minute','分');
INSERT INTO item_counters VALUES('bottle','本');
INSERT INTO item_counters VALUES('tree','本');
INSERT INTO item_counters VALUES('rod','本');
INSERT INTO item_counters VALUES('river','本');
INSERT INTO item_counters VALUES('pen','本');
INSERT INTO item_counters VALUES('line','本');
INSERT INTO item_counters VALUES('o''clock','時');
INSERT INTO item_counters VALUES('day of the month','日');
INSERT INTO item_counters VALUES('company','社');
INSERT INTO item_counters VALUES('shinto shrine','社');
INSERT INTO item_counters VALUES('office building','ヶ所');
INSERT INTO item_counters VALUES('street','本');
INSERT INTO item_counters VALUES('high school','校');
INSERT INTO item_counters VALUES('elementary school','校');
INSERT INTO item_counters VALUES('middle school','校');
INSERT INTO item_counters VALUES('university','校');
INSERT INTO item_counters VALUES('cram school','校');
INSERT INTO item_counters VALUES('pair of mittens','組');
INSERT INTO item_counters VALUES('pair of gloves','組');
INSERT INTO item_counters VALUES('drumset','組');
INSERT INTO item_counters VALUES('deck of cards','組');
INSERT INTO item_counters VALUES('baseball game','試合');
INSERT INTO item_counters VALUES('game','試合');
INSERT INTO item_counters VALUES('match (sports)','試合');
INSERT INTO item_counters VALUES('basketball game','ゲーム');
INSERT INTO item_counters VALUES('fur pelt','枚');
INSERT INTO item_counters VALUES('blanket','枚');
INSERT INTO item_counters VALUES('word','語');
INSERT INTO item_counters VALUES('straw','本');
INSERT INTO item_counters VALUES('bookstore','軒');
INSERT INTO item_counters VALUES('shop','軒');
INSERT INTO item_counters VALUES('store','軒');
INSERT INTO item_counters VALUES('tea house','軒');
INSERT INTO item_counters VALUES('house','軒');
INSERT INTO item_counters VALUES('home','軒');
INSERT INTO item_counters VALUES('barn','軒');
INSERT INTO item_counters VALUES('izakaya','軒');
INSERT INTO item_counters VALUES('apartment','軒');
INSERT INTO item_counters VALUES('cinema','軒');
INSERT INTO item_counters VALUES('arcade','軒');
INSERT INTO item_counters VALUES('nightclub','軒');
INSERT INTO item_counters VALUES('law','件');
INSERT INTO item_counters VALUES('loan','件');
INSERT INTO item_counters VALUES('task','件');
INSERT INTO item_counters VALUES('appointment','件');
INSERT INTO item_counters VALUES('registration','件');
INSERT INTO item_counters VALUES('request','件');
INSERT INTO item_counters VALUES('recommendation','件');
INSERT INTO item_counters VALUES('proverb','語');
INSERT INTO item_counters VALUES('saying','語');
INSERT INTO item_counters VALUES('keyword','語');
INSERT INTO item_counters VALUES('idiom','語');
INSERT INTO item_counters VALUES('serving of yakisoba','皿');
INSERT INTO item_counters VALUES('bowl of soup','皿');
INSERT INTO item_counters VALUES('bowl of fried rice','皿');
INSERT INTO item_counters VALUES('plate of food','皿');
INSERT INTO item_counters VALUES('side dish','皿');
COMMIT;
